; Shared settings used across the script.
global BRIGHTNESS_STEP := 10
global BRIGHTNESS_POPUP_WIDTH := 170
global BRIGHTNESS_POPUP_HEIGHT := 50
global BRIGHTNESS_POPUP_RADIUS := 8
global BRIGHTNESS_POPUP_BAR_WIDTH := 110
global BRIGHTNESS_POPUP_SHADOW_SIZE := 4
global BRIGHTNESS_POPUP_SHADOW_OFFSET_Y := 2
global BRIGHTNESS_POPUP_BAR_COLOR := "" ; Forces the same RGB hex color in all themes.
global BRIGHTNESS_POPUP_BAR_COLOR_LIGHT := "0067C0" ; RGB hex, `#` optional.
global BRIGHTNESS_POPUP_BAR_COLOR_DARK := "60CDFF" ; RGB hex, `#` optional.
global BRIGHTNESS_POPUP_BORDER_COLOR := "" ; Forces the same RGB hex border in all themes.
global BRIGHTNESS_POPUP_BORDER_COLOR_LIGHT := "D7D7D7" ; RGB hex, `#` optional.
global BRIGHTNESS_POPUP_BORDER_COLOR_DARK := "595959" ; RGB hex, `#` optional.
global BRIGHTNESS_POPUP_MARGIN_BOTTOM := 18
global BRIGHTNESS_POPUP_MOTION_OFFSET := 12
global BRIGHTNESS_POPUP_TIMEOUT_MS := 1400
global BRIGHTNESS_POPUP_FADE_INTERVAL_MS := 16
global BRIGHTNESS_POPUP_FADE_IN_STEP := 0.20
global BRIGHTNESS_POPUP_FADE_OUT_STEP := 0.14
global BRIGHTNESS_POPUP_FADE_MIN_ALPHA := 0.22
global BRIGHTNESS_POPUP_RENDER_SCALE := 4
global OSD_TIMEOUT_MS := 1000
global BRIGHTNESS_WMI_PATH := "winmgmts:{impersonationLevel=impersonate}!\\.\root\WMI"
